### ISSUE TITLE
Babel JS Alot of the text is red.

### ISSUE THREAD

**Issue by BannerBomb** [material-theme/vsc-community-material-theme#1]
I know I have mentioned this on the other extension repo,  but I didn't know that there was a place for the Community Material Theme extension also now, anyways on Community Material Theme, almost everything has turned red after the last VSCode update with babel javascript
![image](https://user-images.githubusercontent.com/11788894/76284155-deae9a80-6272-11ea-91ef-77027a488e2a.png)
![image](https://user-images.githubusercontent.com/11788894/76284354-73b19380-6273-11ea-9620-b7b8243f9491.png)
![image](https://user-images.githubusercontent.com/11788894/76284434-ad829a00-6273-11ea-8011-63e784fdbdc3.png)
![image](https://user-images.githubusercontent.com/11788894/76284487-da36b180-6273-11ea-9b6f-06fcfc0f5183.png)

and functions have turned yellow, and object keys have turned white

**Comment by jbkly** [comment]
Noticing the same thing with TypeScript, starting today

**Comment by tehSIRius** [comment]
I've noticed something similar with vanilla JavaScript. A lot of text that used to be blue is now yellow.

**Comment by Coding-Kiwi** [comment]
Confirming, all my calls methods in JavaScript went from blue to yellow.
What I noticed is that when I switch between themes, the methods are blue for a tiny flash and then turn yellow.
Is this some kind of minimum contrast kicking in because the blue is too dark?

**Comment by isinkin** [comment]
add

```json
"editor.semanticHighlighting.enabled": false
```
to settings.json

**Comment by tehSIRius** [comment]
> add
> 
> ```json
> "editor.semanticHighlighting.enabled": false
> ```
> 
> to settings.json

Thanks, that solved it for me

**Comment by ddubrava** [comment]
Is it ok that an extension with over 2kk (not community version) downloads has "one" color scheme for typescript?
imports = operators = interface = generic = methods = decorators etc

**Comment by kangw3n** [comment]
For those who may concern, 
it caused by the new feature from VSC called `Semantic highlighting`


https://github.com/microsoft/vscode/issues/92308#issuecomment-597208066

**Comment by BannerBomb** [comment]
thanks it's fixed after disabling that, I would be nice if it would be set to red if it's not defined instead of red when the value is defined though. 🤷‍♂
