### ISSUE TITLE
[Feature Request] Add dividing lines in different areas

### ISSUE THREAD

**Issue by JemmyWong** [material-theme/vsc-community-material-theme#11]
It's very common to adjust the hight of the console and the width of the active bar. But now it's hard to drag and to adjust, hope your guys can add this feature.

<img width="926" alt="image" src="https://user-images.githubusercontent.com/18246211/90090818-8e72c180-dd57-11ea-8628-e856df80959e.png">

**Comment by Pythians** [comment]
> It's very common to adjust the hight of the console and the width of the active bar. But now it's hard to drag and to adjust, hope your guys can add this feature.
> 
> <img alt="image" width="926" src="https://user-images.githubusercontent.com/18246211/90090818-8e72c180-dd57-11ea-8628-e856df80959e.png">

Which theme do you use?
There should be a high contrast version with this feature.
It looks like you should use `Community Material Theme High Contrast`

**Comment by JemmyWong** [comment]
Thank you @Pythians. I'm using `Community Material Theme`, yeah, `Community Material Theme High Contrast` has the feature I want. But I more like `Community Material Theme`, is there any way to add the feature to this theme?

**Comment by Pythians** [comment]
> Thank you @Pythians. I'm using `Community Material Theme`, yeah, `Community Material Theme High Contrast` has the feature I want. But I more like `Community Material Theme`, is there any way to add the feature to this theme?

like this
![image](https://user-images.githubusercontent.com/7250578/90355451-f8080e00-e07e-11ea-9edb-701353be1ce5.png)
![image](https://user-images.githubusercontent.com/7250578/90355498-18d06380-e07f-11ea-98d3-c261ed580fe0.png)
ignore the status bar

**Comment by JemmyWong** [comment]
Yeah, exactly.

**Comment by JemmyWong** [comment]
It's very cool, how to do this?

**Comment by Pythians** [comment]
Just modify two properties
But I’m not sure to modify the current one, or create a new one @equinusocio 

@JemmyWong You can also modify your local theme easily

**Comment by equinusocio** [comment]
Hello, this is a personal taste. We already added that in the past and while some of the users liked it, most of them don't. So, every personal-taste based modifications must be made by the user using the powerful vscode api. We can't add a variant/option for everyone. 

Please check the "Override theme colors" section in the Readme.

**Comment by Pythians** [comment]
> Hello, this is a personal taste change. We already added that in the past and while some of the users liked it, most of them don't. So, every personal-taste based modifications must be made by the user using the powerful vscode api. We can't add a variant/option for everyone.
> 
> Please check the "Override theme colors" section in the Readme. @Pythians can you provide the keys required to change the separators?

Yeah
```js
"workbench.colorCustomizations": {
    "[Community Material Theme]": {
        "sideBar.border": "#FF000060", //Any color you like
        "panel.border": "#FF000060"  //last screenshot "#00000060"
    },
}
```
![image](https://user-images.githubusercontent.com/7250578/90367007-b71df280-e09a-11ea-9e20-4e48ea4d70d0.png)
@JemmyWong

**Comment by JemmyWong** [comment]
That's great. Thank you guys @Pythians @equinusocio .
