### ISSUE TITLE
My previous settings cannot  be loaded after VSCODE latest update.

### ISSUE THREAD

**Issue by Bayramito** [material-theme/vsc-community-material-theme#2]
Hi,

Today i just updated my VSCODE to the latest version, but seems like my old theme's settings can't load.

They actually being visible at startup of the editor, but after a while changing to random again...

I was using community material theme ocean before.

**Comment by equinusocio** [comment]
Hello, this theme is maintained by community. We suggest to become a contributor or submit a PR by yourself.
