### ISSUE TITLE
How to customize border color?

### ISSUE THREAD

**Issue by farhan2077** [material-theme/vsc-community-material-theme#20]
So basically I want the border color like shown in the image below in red marked area. As far as I know, `vsc-community-material-theme` doesn't currently have one like this. Any help would be appreciated.

[Screenshot is from `dracula` theme]

![2021-03-18-12-21-19](https://user-images.githubusercontent.com/32035481/111582324-dcb3db80-87e4-11eb-850b-52dcb2cdaf12.png)

**EDIT:**

So, in vscode `settings.json` I tried doing this & still nothing has changed even after restarting vscode.
```
  "editor.tokenColorCustomizations": {
    "[Community Material Theme VARIANT]": {
      "editorGroup.border": "#80CBC4",
      "panel.border": "#80CBC4"
    }
  },
```

**Comment by Pythians** [comment]
Hi @farhan2077 use the settings below
```
"workbench.colorCustomizations": {
	"[Community Material Theme VARIANT]": {
		"editorGroup.border": "#80CBC4",
		"panel.border": "#80CBC4"
	}
}
```

These you may need
[How can I change the color of the indent guides?](https://code.visualstudio.com/docs/getstarted/userinterface#_how-can-i-change-the-color-of-the-indent-guides)
[Theme Color](https://code.visualstudio.com/api/references/theme-color)

**Comment by farhan2077** [comment]
Ok got it
