### ISSUE TITLE
Can't install on VSCodium

### ISSUE THREAD

**Issue by Chillstice** [material-theme/vsc-community-material-theme#7]
When trying to use the Material Theme or the Community Material Theme on VSCodium 1.47.2 nothing changes and the following error sometimes displays in the notifications:

`Unable to load file:///c%3A/Users/Chris/.vscode-oss/extensions/equinusocio.vsc-community-material-theme-1.4.1/themes/Community-Material-Theme-Darker.json: Problems parsing JSON theme file: Invalid symbol, Invalid symbol, Invalid symbol, Invalid symbol, Invalid symbol, Invalid symbol, Invalid symbol, Invalid symbol, Invalid symbol, Invalid symbol, Invalid symbol, Invalid symbol, Invalid symbol, Invalid symbol, Invalid symbol, Invalid symbol, Invalid symbol, Invalid symbol, Invalid symbol, Invalid symbol, End of file expected`

**Comment by nicdoye** [comment]
This refers to the version on Open VSX: https://open-vsx.org/api/Equinusocio/vsc-community-material-theme/1.4.1/file/Equinusocio.vsc-community-material-theme-1.4.1.vsix

It appears that every `.json` file in the themes folder is 34235 bytes long, and the UNIX command `file` states they are `openssl enc'd data with salted password, base64 encoded` and not JSON.

The version from the official VS Code Marketplace can be downloaded here: https://marketplace.visualstudio.com/_apis/public/gallery/publishers/Equinusocio/vsextensions/vsc-community-material-theme/1.4.1/vspackage . It's a `.tar.gz`. Copying these files over the top will allow you to get you the theme you desire.
